# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f5acaaef4e23d1b290c832a8ccd913fe1d8131fbdf4272df1aa81e82eeabf10f33ad29fd298f5715df08c16c2c52352a375dd257f585ca349692d0a9cec8405

test:
  secret_key_base: b2993e3bd28b2879c97b9ef2b723d9ba851e462d0795c3325ea17a00c3bc40f702f0cd8d7358b1ad1eacc69283da28576fc8d5c368d5e0c6d0a09614f2587399

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
